### ISSUE TITLE
Upgrade prev message loader function

### ISSUE THREAD

**Issue by alma100** [alma100/chat-app#2]
Server:
1. Created a new endpoint witch handle the old messages request.
2. Created new method which find the current chat messages and after that order by created time, and last split the message and send right sequence to the client.

Client:
1. Split the message list smaller part, and display it. Every time when new message arrive increases the maximum number of messages that can be displayed. If the user start scroll up do the same. When the user reaches the maximum number of loaded message, send a request to the server for next 200 messages.

+ Start refactoring registration component.
+ add progress bar to registration form.
+ add new warning message to registration form (if the pasword format incorrect).
+ saves the data outside the database container.

**Comment by ep-cc** [comment]
Please add a short description above, including a few separate steps, according to our template.
